<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>x86</PlatformTarget>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="PublicApiGenerator" />
		<PackageReference Include="Verify.MSTest" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Skyline.DataMiner.Utils.DOM" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" />
		<PackageReference Include="Microsoft.OpenApi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(RootDir)\UserDefinedApiToolkit\UserDefinedApiToolkit.csproj" />
		<ProjectReference Include="$(RootDir)\UserDefinedApiToolkit.Build\UserDefinedApiToolkit.Build.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="System.Web" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

</Project>
