name: Internal

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Master Workflow.yml@main
    with:
      configuration: Release
      sonarcloud-project-name: ${{ vars.SONAR_NAME }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGETAPIKEY_GITHUB }}