name: Public

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  workflow_dispatch:

jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Master Workflow.yml@main
    with:
      configuration: Release
      sonarcloud-project-name: ${{ vars.SONAR_NAME }}
      nuget-push-source: "https://api.nuget.org/v3/index.json"
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}